// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimecardsData;

#nullable disable

namespace TimecardsData.Migrations
{
    [DbContext(typeof(TimecardsContext))]
    [Migration("20240225214557_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("TimecardsData.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimecardID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("TimecardID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TimecardsData.Timecard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Timecards");
                });

            modelBuilder.Entity("TimecardsData.Activity", b =>
                {
                    b.HasOne("TimecardsData.Timecard", "Timecard")
                        .WithMany("Activities")
                        .HasForeignKey("TimecardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timecard");
                });

            modelBuilder.Entity("TimecardsData.Timecard", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
